[project]
name = "retail-consumer-behavior-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.4.3",
    "marimo>=0.19.5",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
]
